In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
import webbrowser
website = 'https://en.wikipedia.org/wiki/NFL_win%E2%80%93loss_records'
webbrowser.open(website)

True

In [8]:
#copy and read data with pandas
#dataframe is like speradsheet
#pandas autoindexes
nfl_frame =  pd.read_clipboard()

In [9]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
0,1,Chicago Bears,741,555,42,0.570,1920,"1,338",NFC North
1,2,Dallas Cowboys,480,364,6,0.568,1960,850,NFC East
2,3,Green Bay Packers,720,547,37,0.566,1921,"1,304",NFC North
3,4,Miami Dolphins,429,335,4,0.561,1966,768,AFC East
4,5,New England Patriots,462,381,9,0.548,1960,852,AFC East
5,6,San Francisco 49ers,520,436,14,0.543,1950,970,NFC West
6,7,Baltimore Ravens,173,146,1,0.542,1996,320,AFC North
7,8,Minnesota Vikings,449,379,10,0.542,1961,838,NFC North
8,9,New York Giants,673,567,33,0.542,1925,"1,273",NFC East
9,10,Denver Broncos,456,386,10,0.541,1960,852,AFC West
10,11,Indianapolis Colts,494,433,7,0.533,1953,934,AFC South
11,12,Oakland Raiders,444,397,11,0.528,1960,852,AFC West
12,13,Pittsburgh Steelers,590,530,20,0.526,1933,"1,140",AFC North
13,14,Kansas City Chiefs,435,405,12,0.518,1960,852,AFC West
14,15,Washington Redskins,578,565,27,0.506,1932,"1,170",NFC East

In [10]:
nfl_frame.columns

Index([u'Rank', u'Team', u'Won', u'Lost', u'Tied', u'Pct.',
       u'First NFL Season', u'Total Games', u'Division'],
      dtype='object')

In [15]:
nfl_frame['First NFL Season']

0     1920
1     1960
2     1921
3     1966
4     1960
5     1950
6     1996
7     1961
8     1925
9     1960
10    1953
11    1960
12    1933
13    1960
14    1932
Name: First NFL Season, dtype: int64

In [16]:
#Grabbing specified columns

DataFrame(nfl_frame,columns=['Team','First NFL Season','Total Games'])

                    Team  First NFL Season Total Games
0          Chicago Bears              1920       1,338
1         Dallas Cowboys              1960         850
2      Green Bay Packers              1921       1,304
3         Miami Dolphins              1966         768
4   New England Patriots              1960         852
5    San Francisco 49ers              1950         970
6       Baltimore Ravens              1996         320
7      Minnesota Vikings              1961         838
8        New York Giants              1925       1,273
9         Denver Broncos              1960         852
10    Indianapolis Colts              1953         934
11       Oakland Raiders              1960         852
12   Pittsburgh Steelers              1933       1,140
13    Kansas City Chiefs              1960         852
14   Washington Redskins              1932       1,170

In [17]:
#When column doesn't exist in frame, it gives NaN
DataFrame(nfl_frame,columns=['Team','First NFL Season','Total Games','Stadium'])

                    Team  First NFL Season Total Games  Stadium
0          Chicago Bears              1920       1,338      NaN
1         Dallas Cowboys              1960         850      NaN
2      Green Bay Packers              1921       1,304      NaN
3         Miami Dolphins              1966         768      NaN
4   New England Patriots              1960         852      NaN
5    San Francisco 49ers              1950         970      NaN
6       Baltimore Ravens              1996         320      NaN
7      Minnesota Vikings              1961         838      NaN
8        New York Giants              1925       1,273      NaN
9         Denver Broncos              1960         852      NaN
10    Indianapolis Colts              1953         934      NaN
11       Oakland Raiders              1960         852      NaN
12   Pittsburgh Steelers              1933       1,140      NaN
13    Kansas City Chiefs              1960         852      NaN
14   Washington Redskins              1932       1,170      NaN

In [19]:
#returning a few rows
nfl_frame.head(4)

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
0,1,Chicago Bears,741,555,42,0.570,1920,"1,338",NFC North
1,2,Dallas Cowboys,480,364,6,0.568,1960,850,NFC East
2,3,Green Bay Packers,720,547,37,0.566,1921,"1,304",NFC North
3,4,Miami Dolphins,429,335,4,0.561,1966,768,AFC East

In [20]:
nfl_frame.tail(2)

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
13,14,Kansas City Chiefs,435,405,12,0.518,1960,852,AFC West
14,15,Washington Redskins,578,565,27,0.506,1932,"1,170",NFC East

In [21]:
# grab rows on index
nfl_frame.ix[3]

Rank                             4
Team                Miami Dolphins
Won                            429
Lost                           335
Tied                             4
Pct.                         0.561
First NFL Season              1966
Total Games                    768
Division                  AFC East
Name: 3, dtype: object

In [22]:
nfl_frame['Stadium'] = "Levi's Stadium"

In [23]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Chicago Bears,741,555,42,0.570,1920,"1,338",NFC North,Levi's Stadium
1,2,Dallas Cowboys,480,364,6,0.568,1960,850,NFC East,Levi's Stadium
2,3,Green Bay Packers,720,547,37,0.566,1921,"1,304",NFC North,Levi's Stadium
3,4,Miami Dolphins,429,335,4,0.561,1966,768,AFC East,Levi's Stadium
4,5,New England Patriots,462,381,9,0.548,1960,852,AFC East,Levi's Stadium
5,6,San Francisco 49ers,520,436,14,0.543,1950,970,NFC West,Levi's Stadium
6,7,Baltimore Ravens,173,146,1,0.542,1996,320,AFC North,Levi's Stadium
7,8,Minnesota Vikings,449,379,10,0.542,1961,838,NFC North,Levi's Stadium
8,9,New York Giants,673,567,33,0.542,1925,"1,273",NFC East,Levi's Stadium
9,10,Denver Broncos,456,386,10,0.541,1960,852,AFC West,Levi's Stadium
10,11,Indianapolis Colts,494,433,7,0.533,1953,934,AFC South,Levi's Stadium
11,12,Oakland Raiders,444,397,11,0.528,1960,852,AFC West,Levi's Stadium
12,13,Pittsburgh Steelers,590,530,20,0.526,1933,"1,140",AFC North,Levi's Stadium
13,14,Kansas City Chiefs,435,405,12,0.518,1960,852,AFC West,Levi's Stadium
14,15,Washington Redskins,578,565,27,0.506,1932,"1,170",NFC East,Levi's Stadium

In [25]:
nfl_frame['Stadium'] =  np.arange(15)

In [26]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Chicago Bears,741,555,42,0.570,1920,"1,338",NFC North,0
1,2,Dallas Cowboys,480,364,6,0.568,1960,850,NFC East,1
2,3,Green Bay Packers,720,547,37,0.566,1921,"1,304",NFC North,2
3,4,Miami Dolphins,429,335,4,0.561,1966,768,AFC East,3
4,5,New England Patriots,462,381,9,0.548,1960,852,AFC East,4
5,6,San Francisco 49ers,520,436,14,0.543,1950,970,NFC West,5
6,7,Baltimore Ravens,173,146,1,0.542,1996,320,AFC North,6
7,8,Minnesota Vikings,449,379,10,0.542,1961,838,NFC North,7
8,9,New York Giants,673,567,33,0.542,1925,"1,273",NFC East,8
9,10,Denver Broncos,456,386,10,0.541,1960,852,AFC West,9
10,11,Indianapolis Colts,494,433,7,0.533,1953,934,AFC South,10
11,12,Oakland Raiders,444,397,11,0.528,1960,852,AFC West,11
12,13,Pittsburgh Steelers,590,530,20,0.526,1933,"1,140",AFC North,12
13,14,Kansas City Chiefs,435,405,12,0.518,1960,852,AFC West,13
14,15,Washington Redskins,578,565,27,0.506,1932,"1,170",NFC East,14

In [30]:
#add series to dataframe
stadiums = Series(["Levi's Stadium","ATT Stadium"],index=[4,0])

In [31]:
stadiums

4    Levi's Stadium
0       ATT Stadium
dtype: object

In [32]:
nfl_frame['Stadium'] = stadiums

In [33]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Chicago Bears,741,555,42,0.570,1920,"1,338",NFC North,ATT Stadium
1,2,Dallas Cowboys,480,364,6,0.568,1960,850,NFC East,NaN
2,3,Green Bay Packers,720,547,37,0.566,1921,"1,304",NFC North,NaN
3,4,Miami Dolphins,429,335,4,0.561,1966,768,AFC East,NaN
4,5,New England Patriots,462,381,9,0.548,1960,852,AFC East,Levi's Stadium
5,6,San Francisco 49ers,520,436,14,0.543,1950,970,NFC West,NaN
6,7,Baltimore Ravens,173,146,1,0.542,1996,320,AFC North,NaN
7,8,Minnesota Vikings,449,379,10,0.542,1961,838,NFC North,NaN
8,9,New York Giants,673,567,33,0.542,1925,"1,273",NFC East,NaN
9,10,Denver Broncos,456,386,10,0.541,1960,852,AFC West,NaN
10,11,Indianapolis Colts,494,433,7,0.533,1953,934,AFC South,NaN
11,12,Oakland Raiders,444,397,11,0.528,1960,852,AFC West,NaN
12,13,Pittsburgh Steelers,590,530,20,0.526,1933,"1,140",AFC North,NaN
13,14,Kansas City Chiefs,435,405,12,0.518,1960,852,AFC West,NaN
14,15,Washington Redskins,578,565,27,0.506,1932,"1,170",NFC East,NaN

In [34]:
del nfl_frame['Stadium']
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
0,1,Chicago Bears,741,555,42,0.570,1920,"1,338",NFC North
1,2,Dallas Cowboys,480,364,6,0.568,1960,850,NFC East
2,3,Green Bay Packers,720,547,37,0.566,1921,"1,304",NFC North
3,4,Miami Dolphins,429,335,4,0.561,1966,768,AFC East
4,5,New England Patriots,462,381,9,0.548,1960,852,AFC East
5,6,San Francisco 49ers,520,436,14,0.543,1950,970,NFC West
6,7,Baltimore Ravens,173,146,1,0.542,1996,320,AFC North
7,8,Minnesota Vikings,449,379,10,0.542,1961,838,NFC North
8,9,New York Giants,673,567,33,0.542,1925,"1,273",NFC East
9,10,Denver Broncos,456,386,10,0.541,1960,852,AFC West
10,11,Indianapolis Colts,494,433,7,0.533,1953,934,AFC South
11,12,Oakland Raiders,444,397,11,0.528,1960,852,AFC West
12,13,Pittsburgh Steelers,590,530,20,0.526,1933,"1,140",AFC North
13,14,Kansas City Chiefs,435,405,12,0.518,1960,852,AFC West
14,15,Washington Redskins,578,565,27,0.506,1932,"1,170",NFC East

In [36]:
#can construct dataframes by passing in dictionaries
data = {'city':['SF','LA','NYC'],'Population':[837000,3880000,8400000]}

In [37]:
data

{'Population': [837000, 3880000, 8400000], 'city': ['SF', 'LA', 'NYC']}

In [38]:
city_frame = DataFrame(data)

In [39]:
city_frame

   Population city
0      837000   SF
1     3880000   LA
2     8400000  NYC

In [40]:
# wow

In [ ]:
#but what are frames good for?

#more on pandas dataframes, go read the documentation.  Or wait till he explains it :)